"""
Django settings for mcot_rental project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(_=ze02$yfq79kkuw^&ttp9etccb%t=1p7vb=^u6tz%@t70v%0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Allow Serveo.net for tunneling (prevent CSRF Failed: Origin checking failed)
CSRF_TRUSTED_ORIGINS = [
    'https://*.serveo.net',
    'https://*.serveousercontent.com'
]



# Application definition

INSTALLED_APPS = [
    'unfold',  # Django Unfold Theme (Must be before admin)
    'unfold.contrib.filters',  # Optional: Better filters
    'unfold.contrib.forms',    # Optional: Better forms
    'unfold.contrib.inlines',  # Optional: Better inlines
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # For template formatting
    'simple_history',  # Django Simple History for Audit Trail
    'rentals',  # MCOT Enterprise Rental System App
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Enable Translations
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',  # Track user in history
]

ROOT_URLCONF = 'mcot_rental.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mcot_rental.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'th'  # ตั้งค่าภาษาไทย

TIME_ZONE = 'Asia/Bangkok'  # เวลาประเทศไทย

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect to profile page after login
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'  # Redirect to home after logout


# ==============================================================================
# JAZZMIN UI CONFIGURATION - การตั้งค่า Admin Interface สวยงาม
# ==============================================================================

# ==============================================================================
# DJANGO UNFOLD CONFIGURATION - Theming
# ==============================================================================

UNFOLD_SETTINGS = {
    "SITE_TITLE": "MCOT Rental System",
    "SITE_HEADER": "MCOT Enterprise",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("rentals/img/logo.png"),  # example
        "dark": lambda request: static("rentals/img/logo.png"),
    },
    "DASHBOARD_CALLBACK": "rentals.views.dashboard_callback", # Optional
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Navigation",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Go to Site",
                        "icon": "web",
                        "link": "/",
                    },
                ],
            },
        ],
    },
    "STYLES": [
        lambda request: static("rentals/css/admin_theme_v100.css"),
    ],
}

# Jazzmin settings removed.


CART_SESSION_ID = 'cart'

# Media files (User uploaded)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================================================================
# EXTERNAL INTEGRATIONS
# ==============================================================================

# Line Notify Token (Get from https://notify-bot.line.me/my/)
LINE_NOTIFY_TOKEN = ''  # ใส่ Token ที่นี่ (หรืออ่านจาก Env Var)

