"""
Django settings for mcot_rental project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(_=ze02$yfq79kkuw^&ttp9etccb%t=1p7vb=^u6tz%@t70v%0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Allow Serveo.net for tunneling (prevent CSRF Failed: Origin checking failed)
CSRF_TRUSTED_ORIGINS = [
    'https://*.serveo.net',
    'https://*.serveousercontent.com'
]



# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Modern Admin UI - ต้องอยู่ก่อน django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # For template formatting
    'simple_history',  # Django Simple History for Audit Trail
    'rentals',  # MCOT Enterprise Rental System App
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Enable Translations
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',  # Track user in history
]

ROOT_URLCONF = 'mcot_rental.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mcot_rental.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'th'  # ตั้งค่าภาษาไทย

TIME_ZONE = 'Asia/Bangkok'  # เวลาประเทศไทย

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect to profile page after login
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'  # Redirect to home after logout


# ==============================================================================
# JAZZMIN UI CONFIGURATION - การตั้งค่า Admin Interface สวยงาม
# ==============================================================================

JAZZMIN_SETTINGS = {
    # ชื่อระบบ
    "site_title": "MCOT Rental System",
    "site_header": "🎬 MCOT Enterprise",
    "site_brand": "MCOT Rental System",
    "welcome_sign": "ยินดีต้อนรับสู่ระบบจัดการการเช่าอุปกรณ์ MCOT",
    
    # โลโก้
    "site_logo": None,
    "site_icon": None,
    
    # ข้อความ copyright
    "copyright": "MCOT Enterprise Rental System 2025",
    
    # ปิด Google Font โหลดเร็วขึ้น
    "use_google_fonts_cdn": False,
    
    # ธีมสี
    "show_ui_builder": False,
    "changeform_format": "single", # ปิด Tabs ของ Jazzmin เพื่อใช้ Custom Dashboard
    
    # เมนูด้านซ้าย
    "topmenu_links": [
        {"name": "📊 Dashboard", "url": "/staff/dashboard/"},
        {"name": "📅 ปฏิทิน", "url": "calendar"},
        {"name": "⚙️ System Admin", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    
    # ลำดับการแสดงในเมนู
    "order_with_respect_to": [
        "rentals",
        "auth",
        "simple_history",
    ],
    
    # ไอคอนสำหรับแต่ละโมเดล
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "rentals.booking": "fas fa-calendar-check",
        "rentals.equipment": "fas fa-video",
        "rentals.studio": "fas fa-door-open",
        "rentals.staff": "fas fa-user-tie",
        
        "rentals.historicalbooking": "fas fa-history",
        "rentals.historical equipment": "fas fa-history",
        "rentals.historicalstudio": "fas fa-history",
        "rentals.historicalstaff": "fas fa-history",
    },
    
    # ธีมสีหลัก
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # ปรับแต่งเมนู
    "custom_css": "rentals/css/admin_custom_v2.css",  # Premium Modern Admin Theme (Cache Busted)
    "custom_js": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # ซ่อนโมเดลที่ไม่ต้องการ
    "hide_apps": [],
    "hide_models": [],
    
    # ภาษาไทย
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

CART_SESSION_ID = 'cart'

# Media files (User uploaded)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================================================================
# EXTERNAL INTEGRATIONS
# ==============================================================================

# Line Notify Token (Get from https://notify-bot.line.me/my/)
LINE_NOTIFY_TOKEN = ''  # ใส่ Token ที่นี่ (หรืออ่านจาก Env Var)

