# Generated by Django 4.2.27 on 2026-01-06 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0003_booking_customer_email_booking_customer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อปัญหา')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('priority', models.CharField(choices=[('low', 'Low (ต่ำ)'), ('medium', 'Medium (กลาง)'), ('high', 'High (สูง)'), ('critical', 'Critical (ด่วนที่สุด)')], default='medium', max_length=20, verbose_name='ความสำคัญ')),
                ('status', models.CharField(choices=[('new', 'New (แจ้งใหม่)'), ('investigating', 'Investigating (กำลังตรวจสอบ)'), ('fixed', 'Fixed (แก้ไขแล้ว)'), ('closed', 'Closed (ปิดงาน)')], default='new', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่แจ้ง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.equipment', verbose_name='อุปกรณ์ที่เกี่ยวข้อง (ถ้ามี)')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้แจ้ง')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.studio', verbose_name='สตูดิโอที่เกี่ยวข้อง (ถ้ามี)')),
            ],
            options={
                'verbose_name': 'แจ้งปัญหา',
                'verbose_name_plural': 'รายการแจ้งปัญหา',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalIssueReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อปัญหา')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('priority', models.CharField(choices=[('low', 'Low (ต่ำ)'), ('medium', 'Medium (กลาง)'), ('high', 'High (สูง)'), ('critical', 'Critical (ด่วนที่สุด)')], default='medium', max_length=20, verbose_name='ความสำคัญ')),
                ('status', models.CharField(choices=[('new', 'New (แจ้งใหม่)'), ('investigating', 'Investigating (กำลังตรวจสอบ)'), ('fixed', 'Fixed (แก้ไขแล้ว)'), ('closed', 'Closed (ปิดงาน)')], default='new', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='วันที่แจ้ง')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='อัปเดตล่าสุด')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rentals.equipment', verbose_name='อุปกรณ์ที่เกี่ยวข้อง (ถ้ามี)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แจ้ง')),
                ('studio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rentals.studio', verbose_name='สตูดิโอที่เกี่ยวข้อง (ถ้ามี)')),
            ],
            options={
                'verbose_name': 'historical แจ้งปัญหา',
                'verbose_name_plural': 'historical รายการแจ้งปัญหา',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
