# Generated by Django 4.2.27 on 2026-01-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_booking_created_by_equipment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('camera', 'กล้อง (Camera)'), ('lens', 'เลนส์ (Lens)'), ('lighting', 'ไฟ (Lighting)'), ('sound', 'เสียง (Sound)'), ('grip', 'อุปกรณ์ประกอบ (Grip)'), ('other', 'อื่นๆ (Other)')], default='other', max_length=50, verbose_name='หมวดหมู่'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='category',
            field=models.CharField(choices=[('camera', 'กล้อง (Camera)'), ('lens', 'เลนส์ (Lens)'), ('lighting', 'ไฟ (Lighting)'), ('sound', 'เสียง (Sound)'), ('grip', 'อุปกรณ์ประกอบ (Grip)'), ('other', 'อื่นๆ (Other)')], default='other', max_length=50, verbose_name='หมวดหมู่'),
        ),
    ]
