# Generated by Django 4.2.27 on 2026-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_equipment_category_historicalequipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด'),
        ),
    ]
