# Generated by Django 4.2.27 on 2026-01-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='รูปภาพ'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='รูปภาพ'),
        ),
        migrations.AddField(
            model_name='historicalstudio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AddField(
            model_name='historicalstudio',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='รูปภาพ'),
        ),
        migrations.AddField(
            model_name='studio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AddField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studios/', verbose_name='รูปภาพ'),
        ),
    ]
