# Generated by Django 4.2.27 on 2026-01-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_historicalissuereport_booking_issuereport_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('category', models.CharField(choices=[('camera', 'กล้อง (Camera)'), ('lens', 'เลนส์ (Lens)'), ('lighting', 'ไฟ (Lighting)'), ('sound', 'เสียง (Sound)'), ('grip', 'อุปกรณ์ประกอบ (Grip)'), ('other', 'อื่นๆ (Other)')], default='other', max_length=50, verbose_name='หมวดหมู่')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเช่าต่อวัน')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวนทั้งหมด')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้เช่า')),
            ],
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['product__name', 'serial_number'], 'verbose_name': 'อุปกรณ์ (Item)', 'verbose_name_plural': 'อุปกรณ์ (Items)'},
        ),
        migrations.AlterModelOptions(
            name='historicalequipment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical อุปกรณ์ (Item)', 'verbose_name_plural': 'historical อุปกรณ์ (Items)'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='name',
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='ราคาต่อหน่วย ณ วันที่จอง', max_digits=10, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.product')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.product', verbose_name='สินค้า (Product)'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rentals.product', verbose_name='สินค้า (Product)'),
        ),
    ]
