# Generated by Django 4.2.27 on 2026-01-09 07:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_package_packageitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-id'], 'verbose_name': 'การจอง', 'verbose_name_plural': 'การจอง'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['product__name', 'serial_number'], 'verbose_name': 'รายการอุปกรณ์ (Equipment)', 'verbose_name_plural': 'รายการอุปกรณ์ (Equipment Items)'},
        ),
        migrations.AlterModelOptions(
            name='historicalequipment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical รายการอุปกรณ์ (Equipment)', 'verbose_name_plural': 'historical รายการอุปกรณ์ (Equipment Items)'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'คลังอุปกรณ์ (Inventory)', 'verbose_name_plural': 'คลังอุปกรณ์ (Inventory)'},
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='สร้างเมื่อ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 9, 7, 20, 17, 206068, tzinfo=datetime.timezone.utc), editable=False, verbose_name='สร้างเมื่อ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 9, 7, 20, 33, 660425, tzinfo=datetime.timezone.utc), editable=False, verbose_name='แก้ไขล่าสุด'),
            preserve_default=False,
        ),
    ]
