# Generated by Django 4.2.27 on 2026-01-12 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0015_alter_booking_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'การจอง', 'verbose_name_plural': 'การจอง'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['product__name', 'serial_number'], 'verbose_name': 'อุปกรณ์รายชิ้น', 'verbose_name_plural': 'อุปกรณ์รายชิ้น'},
        ),
        migrations.AlterModelOptions(
            name='historicalequipment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical อุปกรณ์รายชิ้น', 'verbose_name_plural': 'historical อุปกรณ์รายชิ้น'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'สินค้า (Product)', 'verbose_name_plural': 'สินค้า (Product)'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'พร้อมใช้งาน (Available)'), ('maintenance', 'ส่งซ่อม (Maintenance)'), ('lost', 'สูญหาย (Lost)')], default='available', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='status',
            field=models.CharField(choices=[('available', 'พร้อมใช้งาน (Available)'), ('maintenance', 'ส่งซ่อม (Maintenance)'), ('lost', 'สูญหาย (Lost)')], default='available', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='position',
            field=models.CharField(choices=[('cameraman', 'ช่างภาพ (Cameraman)'), ('sound', 'ช่างเสียง (Sound)'), ('lighting', 'ช่างไฟ (Lighting)'), ('producer', 'โปรดิวเซอร์ (Producer)')], max_length=50, verbose_name='ตำแหน่ง'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('cameraman', 'ช่างภาพ (Cameraman)'), ('sound', 'ช่างเสียง (Sound)'), ('lighting', 'ช่างไฟ (Lighting)'), ('producer', 'โปรดิวเซอร์ (Producer)')], max_length=50, verbose_name='ตำแหน่ง'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='ข้อความ')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='ลิงก์')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('notification_type', models.CharField(choices=[('info', 'ข้อมูล (Info)'), ('success', 'สำเร็จ (Success)'), ('warning', 'เตือน (Warning)'), ('error', 'ข้อผิดพลาด (Error)')], default='info', max_length=20, verbose_name='ประเภท')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่สร้าง')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
    ]
