# Generated by Django 4.2.27 on 2026-01-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_alter_booking_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_highlight',
            field=models.BooleanField(default=False, help_text='ติ๊กเลือกเมื่อต้องการให้เป็นสินค้าแนะนำ (กรอบม่วง)', verbose_name='แนะนำ (Highlight)'),
        ),
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.CharField(blank=True, help_text='ตัวอย่าง: สำหรับงานสัมภาษณ์ / Vlog', max_length=200, verbose_name='คำอธิบายสั้น'),
        ),
    ]
