# Generated by Django 4.2.27 on 2026-01-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_package_is_highlight_package_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'สอบถาม / รอใบเสนอราคา (Draft)'), ('quotation_sent', 'ส่งใบเสนอราคาแล้ว (Quotation Sent)'), ('pending_deposit', 'รอชำระเงินมัดจำ (Waiting for Deposit)'), ('approved', 'ยืนยันแล้ว / รอรับของ (Approved)'), ('active', 'กำลังใช้งาน (Active)'), ('completed', 'จบงาน / คืนของแล้ว (Completed)'), ('problem', 'มีปัญหา / แจ้งซ่อม (Problem)')], default='draft', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='status',
            field=models.CharField(choices=[('draft', 'สอบถาม / รอใบเสนอราคา (Draft)'), ('quotation_sent', 'ส่งใบเสนอราคาแล้ว (Quotation Sent)'), ('pending_deposit', 'รอชำระเงินมัดจำ (Waiting for Deposit)'), ('approved', 'ยืนยันแล้ว / รอรับของ (Approved)'), ('active', 'กำลังใช้งาน (Active)'), ('completed', 'จบงาน / คืนของแล้ว (Completed)'), ('problem', 'มีปัญหา / แจ้งซ่อม (Problem)')], default='draft', max_length=20, verbose_name='สถานะ'),
        ),
    ]
