# Generated by Django 4.2.27 on 2025-12-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่ออุปกรณ์')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='หมายเลขซีเรียล')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเช่าต่อวัน')),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('lost', 'Lost')], default='available', max_length=20, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'อุปกรณ์',
                'verbose_name_plural': 'อุปกรณ์',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อพนักงาน')),
                ('position', models.CharField(choices=[('cameraman', 'Cameraman'), ('sound', 'Sound'), ('lighting', 'Lighting'), ('producer', 'Producer')], max_length=50, verbose_name='ตำแหน่ง')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'พนักงาน',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสตูดิโอ')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเช่าต่อวัน')),
            ],
            options={
                'verbose_name': 'สตูดิโอ',
                'verbose_name_plural': 'สตูดิโอ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ชื่อลูกค้า')),
                ('start_time', models.DateTimeField(verbose_name='วันเวลาเริ่มต้น')),
                ('end_time', models.DateTimeField(verbose_name='วันเวลาสิ้นสุด')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('equipment', models.ManyToManyField(blank=True, related_name='bookings', to='rentals.equipment', verbose_name='อุปกรณ์')),
                ('staff', models.ManyToManyField(blank=True, related_name='bookings', to='rentals.staff', verbose_name='พนักงาน')),
                ('studios', models.ManyToManyField(blank=True, related_name='bookings', to='rentals.studio', verbose_name='สตูดิโอ')),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจอง',
                'ordering': ['-start_time'],
            },
        ),
    ]
