# Generated by Django 4.2.27 on 2026-01-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่ลูกค้า'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่ลูกค้า'),
        ),
    ]
