# Generated by Django 4.2.27 on 2026-01-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_booking_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/', verbose_name='สลิปโอนเงิน'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='payment_slip',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='สลิปโอนเงิน'),
        ),
    ]
