# Generated by Django 4.2.27 on 2026-01-08 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_booking_payment_slip_historicalbooking_payment_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissuereport',
            name='booking',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rentals.booking', verbose_name='การจองที่เกี่ยวข้อง (ถ้ามี)'),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.booking', verbose_name='การจองที่เกี่ยวข้อง (ถ้ามี)'),
        ),
    ]
