# Generated by Django 4.2.27 on 2026-01-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_product_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อแพ็คเกจ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเหมาจ่าย')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='รูปภาพแพ็คเกจ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.product', verbose_name='สินค้า')),
            ],
        ),
    ]
